---
title: "Use-case: evaluation of network inference"
author: "Robrecht Cannoodt"
output: rmarkdown::html_vignette
vignette: >
  \usepackage[utf8]{inputenc}
  %\VignetteIndexEntry{Use-case: evaluation of network inference}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dyngen)

set.seed(1)

backbone <- backbone_bifurcating_cycle()
num_kos <- 40
model <- 
  initialise_model(
    num_cells = 1000,
    num_tfs = 200,
    num_targets = 900,
    num_hks = 900,
    distance_metric = "pearson",
    backbone = backbone,
    tf_network_params = tf_network_default(min_tfs_per_module = 2, sample_num_regulators = function() 2),
    feature_network_params = feature_network_default(target_resampling = 5000),
    kinetics_params = kinetics_default(),
    gold_standard_params = gold_standard_default(),
    simulation_params = simulation_default(
      census_interval = 1,
      burn_time = simtime_from_backbone(backbone, TRUE),
      total_time = simtime_from_backbone(backbone),
      experiment_params = bind_rows(
        simulation_type_wild_type(num_simulations = 32),
        simulation_type_knockdown(num_simulations = num_kos, num_genes = sample(1:10, num_kos, replace = TRUE))
      ),
      store_reaction_propensities = TRUE,
      store_grn = TRUE
    ),
    experiment_params = experiment_snapshot(),
    verbose = TRUE,
    download_cache_dir = "~/.cache/dyngen",
    num_cores = 8
  )

model <- model %>% 
  generate_tf_network() %>% 
  generate_feature_network() %>% 
  generate_kinetics() %>% 
  generate_gold_standard() %>%
  generate_cells() %>% 
  generate_experiment()

traj <- 
  model %>% 
  wrap_dataset(store_grn = TRUE)

traj$expression

reactions <- model$simulation_system$reactions 
names(reactions) <- map_chr(reactions, "name")

comp_reac <- dyngen:::.generate_cells_precompile_reactions(model)
sim <- dyngen:::.generate_cells_simulate_cell(
  simulation_i = 1, model, comp_reac, debug = TRUE
)

feature_network <- model$feature_network

knockouts <- 
  bind_rows(pbapply::pblapply(
    seq_len(nrow(feature_network)), 
    function(i) {
      from <- feature_network$from[[i]]
      to <- feature_network$to[[i]]
      reac_ix <- match(paste0("transcription_", to), comp_reac$reaction_ids)
      from_ix <- match(paste0("y_", from), names(sim$initial_state))
      
      sim$state <- model$simulations$counts[traj$cell_info$step_ix[[1]],] %>% unname
      sim$calculate_propensity()
      
      orig_prop <- sim$propensity[[reac_ix]]
      
      sim$state[[from_ix]] <- 0
      sim$calculate_propensity()
      new_prop <- sim$propensity[[reac_ix]]
      
      tibble(
        i,
        from,
        to,
        orig_prop,
        new_prop,
        reg_effect = orig_prop - new_prop,
        buffer_val = traj$feature_network_sc[1,paste0("regulation_", from, "_", to)]
      )
    }
  ))
fito <- model$feature_info %>% slice(match(knockouts$to, feature_id)) %>% 
  mutate(label = ifelse(is.na(module_id), gsub("[0-9]*$", "", feature_id), gsub("[0-9]*$", "", module_id)))
ggplot(knockouts) +
  geom_point(aes(log10(buffer_val), reg_effect / fito$wpr, colour = fito$label)) +
  theme_bw()

ggplot(knockouts) +
  geom_point(aes((buffer_val), reg_effect / fito$wpr, colour = factor(fito$basal))) +
  theme_bw() +
  scale_x_log10()
```
